using UnityEngine;
using System;
using System.Collections.Generic;
using Random = UnityEngine.Random;
using System.Linq;
using Completed;
using UnityEngine.Assertions.Must;

public class BoardManager : MonoBehaviour
{
    [Serializable]
    public class Count
    {
        public int minimum;
        public int maximum;

        public Count (int min, int max)
        {
            minimum = min;
            maximum = max;
        }
    }

    // Variable declarations

    // Game board dimensions
    public int columns = 8;
    public int rows = 8;

    // Random number of walls per level, between 5 and 9 walls
    public Count wallCount = new Count(5, 9);

    // Same for food items, between 1 and 5
    public Count foodCount = new Count(1, 5);

    // Declare variables to hold prefabs that we will spawn
    public GameObject exit;
    public GameObject[] floorTiles;
    public GameObject[] wallTiles;
    public GameObject[] outerWallTiles;
    public GameObject[] enemyTiles;
    public GameObject[] foodTiles;

    // Private variables
    // This one is so we can child all of the things we spawn so it doesn't muck up the hierarchy
    private Transform boardHolder;
    // Used to track all of the different positions on the game board and whether an object has been spawned in that position
    private List<Vector3> gridPositions = new List<Vector3>();

    // Function to initialize grid positions
    void InitializeList()
    {
        // Clear em all out first
        gridPositions.Clear();

        // Now create a nested loop to populate the grid squares
        for (int x = 1; x < columns - 1; x++)
        {
            for (int y = 1; y < rows - 1; y++)
            {
                gridPositions.Add(new Vector3(x, y, 0f));
            }
        }
    }

    // Board setup function. Laying outer wall tiles and floor tiles.
    void BoardSetup ()
    {
        boardHolder = new GameObject ("Board").transform;

        // Building an edge around the board using the outer wall objects
        for (int x = -1; x < columns + 1; x++)
        {
            for (int y = -1; y < rows + 1; y++)
            {
                GameObject toInstantiate = floorTiles[Random.Range(0, floorTiles.Length)];
                // Check to see if we're in an outer wall position, and if so, use an outer wall tile
                if (x == -1 || x == columns || y == -1 || y == rows)
                {
                    toInstantiate = outerWallTiles[Random.Range(0, outerWallTiles.Length)];
                }

                    // Assign the GameObject "instance" to what we are instantiating
                    GameObject instance = Instantiate(toInstantiate, new Vector3(x, y, 0f), Quaternion.identity) as GameObject;

                    // Set the parent of our newly instantiated game object to boardHolder
                    instance.transform.SetParent(boardHolder);
            }
        }
    }

    // function to generate random positions for spawning things
    Vector3 RandomPosition()
    {
        int randomIndex = Random.Range(0, gridPositions.Count);
        Vector3 randomPosition = gridPositions[randomIndex];
        // need to make sure we don't spawn two objects in the same location, so remove position
        gridPositions.RemoveAt(randomIndex);
        // return the value to spawn our objects on our gameboard
        return randomPosition;
    }

    // function to spawn tiles at random position generated by function above
    void LayoutObjectAtRandom(GameObject[] tileArray, int minimum, int maximum)
    {
        // objectCount will control how many of a given object we will spawn
        int objectCount = Random.Range(minimum, maximum + 1);

        // for loop to spawn number of objects in objectCount
        for (int i = 0; i < objectCount; i++)
        {
            // choose random position to spawn at
            Vector3 randomPosition = RandomPosition();
            // choose a random tile from our array of GameObjects
            GameObject tileChoice = tileArray[Random.Range(0, tileArray.Length)];
            // now instantiate chosen tile at random position
            Instantiate(tileChoice, randomPosition, Quaternion.identity);
        }

    }
    
    // function to setup scene based off level. Will be called by GameManager when it's time to setup the board
    public void SetupScene (int level)
    {
        BoardSetup();
        InitializeList();
        // layout wall tiles
        LayoutObjectAtRandom(wallTiles, wallCount.minimum, wallCount.maximum);
        // layout food doing same
        LayoutObjectAtRandom(foodTiles, foodCount.minimum, foodCount.maximum);
        // instead of random enemy count, will use a logarithmic function so as to increase difficulty based on level
        int enemyCount = (int)Mathf.Log(level, 2f);
        // layout enemies
        LayoutObjectAtRandom(enemyTiles, enemyCount, enemyCount);
        // instantiate the exit which will always be in the same place (upper right hand corner) and be the same object
        Instantiate(exit, new Vector3(columns - 1, rows - 1, 0f), Quaternion.identity);

    }
}
